// <auto-generated />
using DA205E_Assignment6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DA205E_Assignment6.Migrations
{
    [DbContext(typeof(LiteratureAppContext))]
    [Migration("20260602162851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CourseLiterature", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiteratureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesId", "LiteratureId");

                    b.HasIndex("LiteratureId");

                    b.ToTable("CourseLiterature");
                });

            modelBuilder.Entity("DA205E_Assignment6.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DA205E_Assignment6.Models.Literature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearPublished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Literatures");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Literature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DA205E_Assignment6.Models.Book", b =>
                {
                    b.HasBaseType("DA205E_Assignment6.Models.Literature");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("DA205E_Assignment6.Models.JournalArticle", b =>
                {
                    b.HasBaseType("DA205E_Assignment6.Models.Literature");

                    b.Property<int>("Issue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("JournalArticle");
                });

            modelBuilder.Entity("CourseLiterature", b =>
                {
                    b.HasOne("DA205E_Assignment6.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA205E_Assignment6.Models.Literature", null)
                        .WithMany()
                        .HasForeignKey("LiteratureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
